### ISSUE TITLE
'lxml.etree._Element' object has no attribute 'pPr'

### ISSUE THREAD

**Issue by lavishsaluja** [microsoft/Simplify-Docx#6]
I'm trying to read this file: [diary.docx](https://github.com/microsoft/Simplify-Docx/files/5147348/diary.docx), and getting AttributeError on line 56 of [paragraph style](https://github.com/microsoft/Simplify-Docx/blob/master/src/simplify_docx/utils/paragrapy_style.py#L56)

I tried to print different variables and _num_style_ inside _get_paragraph_ind_ is being returned as _NoneType_ by the function _get_num_style_ even when the _p.pPr_ value is not null so most probably it's not able to find any _subElement_ for _abstractNumbering_

Will be great if someone can help me resolve this 🙏

I've attached the docx file I'm using and a screenshot of the Error message below:

<img width="831" alt="Screenshot 2020-08-31 at 1 10 00 AM" src="https://user-images.githubusercontent.com/25464742/91668038-b3707e00-eb26-11ea-871b-f66f91b16025.png">

**Comment by lavishsaluja** [comment]
forgot to add my code snippet, adding it here

```
import docx
from simplify_docx import simplify

doc = docx.Document("/Users/lavishsaluja/Downloads/diary.docx")

json_doc = simplify(doc)
```

**Comment by emremangir** [comment]
Can confirm this issue is happening to me as well

OS: Mac Catalina 10.15.5
Word Version: 16.16.25

Steps to replicate:
1. Create a new document in Word
2. Add numbering to any paragraph
3. Save document
(example attached)
[Sample Document.docx](https://github.com/microsoft/Simplify-Docx/files/5163603/Sample.Document.docx)

Issue seems to start here: https://github.com/microsoft/Simplify-Docx/blob/ce493b60e3e4308bde7399257426c0c68a6c699b/src/simplify_docx/utils/paragrapy_style.py#L54

In particular, it seems that although 
`num_style is not None`, 
the element doesn't have a pPr attribute.

If you bypass:
https://github.com/microsoft/Simplify-Docx/blob/ce493b60e3e4308bde7399257426c0c68a6c699b/src/simplify_docx/utils/paragrapy_style.py#L55-L58
(e.g.)
```
    if num_style is not None:
        try:
            if num_style.pPr is not None and \
            num_style.pPr.ind is not None:
                return num_style.pPr.ind
        except AttributeError:
            return None
```
Then the script runs without error, although style-related information doesn't get pulled in...

**Comment by kdeasymoneysniper** [comment]
hi, this is still happening to me, can i know if theres something im doing wrongly?
